spring.application.name=Trainee_assignment
server.port=8084

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=shreya123
spring.datasource.url=jdbc:mysql://localhost:3306/Book
#hibernate properties:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
